version: "3"

services:
  kvs-server-seed:
    # hostname is needed to define a known docker hostname that is used as the seed hostname.
    hostname: kvs-server-seed
    build: .
    image: kvs-server
    environment:
      TZ: 'Europe/Paris'
    command: ["sleep 300"]