---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Installing packages for administration 
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes

- name: Install Docker Module for Python
  pip:
    name: "{{ python_packages }}"
    executable: pip3

# Install docker
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present


- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

# Install docker-compose
- name: Get docker-compose release
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '+x'
  
