FROM gradle:7.1.1-jdk11 AS build
COPY . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle {% for name in target_mains %} jar{{name[0]|capitalize}}{{substring(1,strlen(name), name)}}{%endfor%}

FROM openjdk:11.0.13-jre-buster
COPY --from=build /home/gradle/src/build/libs/* /bin/{{project_name}}/
WORKDIR /bin/{{project_name}}
EXPOSE 25520/tcp
EXPOSE 8080/tcp
ENTRYPOINT ["/bin/bash"]
#CMD ["--help"]