default: build 

{% for main in target_mains %}
build_{{main.name}}:
	gradle -x test jar{{main.name[0]|capitalize}}{{substring(1,strlen(main.name), main.name)}} 
{% endfor %}

build: protobuf {% for main in target_mains %} build_{{main.name}}{%endfor%}

.PHONY:protobuf
protobuf:
	gradle wrapper
	./gradlew build -x test

.PHONY: test
test:
	gradle test