default: build 

{% for name in target_mains %}
build_{{name}}:
	gradle jar{{name[0]|capitalize}}{{substring(1,strlen(name), name)}} 
{% endfor %}

build:{% for name in target_mains %} build_{{name}}{%endfor%}

.PHONY:build_protobuf
build_protobuf:
	gradle wrapper
	./gradlew build

.PHONY: test
test:
	gradle test